import type { Metadata } from 'next'
import './globals.scss'
import Header from 'src/components/ui/layout/header'
import Footer from 'src/components/ui/layout/footer'
import ParticlesBackground from 'src/components/ui/layout/particles'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
        <ParticlesBackground />
      </body>
    </html>
  )
}
